# Generated by Django 4.2.7 on 2023-11-23 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Unit', '0002_initial'),
        ('School', '0001_initial'),
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('day', models.CharField(max_length=10)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.department')),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Room.room')),
                ('SemesterUnit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Unit.semesterunit')),
            ],
        ),
    ]
