# Generated by Django 5.0.2 on 2024-02-10 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("School", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accepted", models.BooleanField(default=False)),
                (
                    "Department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="School.department",
                    ),
                ),
            ],
        ),
    ]
