# Generated by Django 4.2.7 on 2023-11-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
