# Generated by Django 4.2.7 on 2024-01-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Schedule', '0001_initial'),
        ('Unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='Lectures',
            field=models.ManyToManyField(to='Unit.lecture'),
        ),
    ]
