# Generated by Django 4.2.7 on 2024-01-17 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0001_initial'),
        ('Room', '0001_initial'),
        ('Schedule', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='School.department')),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Room.room')),
            ],
        ),
    ]
