# Generated by Django 4.2.7 on 2023-11-25 15:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0004_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='Lectures',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=['ajsja', ''], size=None),
            preserve_default=False,
        ),
    ]
