# Generated by Django 4.2.7 on 2023-11-25 17:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0005_schedule_lectures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='Lectures',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None),
        ),
    ]
