# Generated by Django 4.2.7 on 2023-11-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unit', '0003_lecture'),
        ('Schedule', '0007_remove_schedule_lectures_delete_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='Lectures',
            field=models.ManyToManyField(to='Unit.lecture'),
        ),
    ]
