# Generated by Django 5.0.2 on 2024-02-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='day_pref',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='time_pref',
            field=models.IntegerField(blank=True, choices=[(8, 'Morning'), (10, 'Mid-Morning'), (14, 'Afternoon')], null=True),
        ),
    ]
