# Generated by Django 4.2.7 on 2024-01-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0001_initial'),
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='Schools',
            field=models.ManyToManyField(blank=True, to='School.school'),
        ),
    ]
