# Generated by Django 4.2.7 on 2024-01-10 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('School', '0001_initial'),
        ('Unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterunit',
            name='Lecturer',
            field=models.ForeignKey(limit_choices_to={'group': 'lecturer'}, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='semesterunit',
            name='Unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Unit.unit'),
        ),
        migrations.AddField(
            model_name='semesterunit',
            name='Year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='School.year'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='SemesterUnit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unit.semesterunit'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='Year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='School.year'),
        ),
    ]
