# Generated by Django 4.2.7 on 2023-11-23 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterunit',
            name='Lecturer',
            field=models.ForeignKey(limit_choices_to={'group': 'lecturer'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='semesterunit',
            name='Unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unit.unit'),
        ),
    ]
