# Generated by Django 4.2.7 on 2024-01-10 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Unit', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='Year',
        ),
    ]
