# Generated by Django 5.0.2 on 2024-02-25 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0001_initial'),
        ('Unit', '0005_semesterunit_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='Room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Room.room'),
            preserve_default=False,
        ),
    ]
